# Generated by Django 5.0.4 on 2024-04-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('object_name', models.CharField(max_length=100, verbose_name='Объект')),
                ('square_meters', models.FloatField(verbose_name='Кв м квартиры')),
                ('date', models.DateField(verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('status', models.CharField(choices=[('Активно', 'Активно'), ('Бронь', 'Бронь'), ('Куплено', 'Куплено'), ('Рассрочка', 'Рассрочка'), ('Бартер', 'Бартер')], default='Активно', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='номер')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('temporary_password', models.CharField(max_length=20, verbose_name='временный пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('contract_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Активно', 'Активно'), ('Бронь', 'Бронь'), ('Куплено', 'Куплено'), ('Рассрочка', 'Рассрочка'), ('Бартер', 'Бартер')], max_length=20)),
                ('date', models.DateField(verbose_name='Дата')),
                ('apartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='flat.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='flat.client'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=500)),
                ('date', models.DateField(verbose_name='Дата')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flat.apartment')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flat.manager')),
            ],
        ),
    ]
