# Generated by Django 5.0.4 on 2024-04-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='apartment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='flat.apartment'),
        ),
    ]
